language: python
os:
  - linux
dist: bionic
matrix:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "pypy2"
    - python: "pypy3"
install:
  - pip install flake8 virtualenv pytest
script:
  - python -V
  - echo "running flake"; flake8 --ignore=E501,W504 --exclude=tests/guinea-pigs;
  - python setup.py test
